{{- if .Values.provision.common.bmcSecret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.provision.common.bmcSecret.name }}
  finalizers: [ "showcase.tinkerbell.org/bmc-required-for-deletion" ]
type: Opaque
data:
{{- range $key, $value := .Values.provision.common.bmcSecret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}